Glog 37 make featured carousel as seen in the figma
HunchMenz/GamingLoggingApp pull request #15
Opened 2022-07-23 03:15 UTC by Chris-Boho

2022-07-23 04:01 UTC, Jhavaa requested changes
We walked through a bit of it together, so the style is O.K. with me... BUT!... There are some bugs I found:

1. There is an issue with poster not recognizing the cover property, cause some calls are still passing 'image' as an object parameter.
2. The text summary should be left aligned. After looking at it a bit more, I feel like it'll look nicer left-aligned.
3. It would be awesome if you can implement auto sliding to the feature slider. I looked through the docs and found the [autoplay](https://swiperjs.com/swiper-api#autoplay) parameter that does just this. Take a look and see if we can implement that feature.

I'll continue to review the code, so these are just issues observed from running the branch and I _might_ find something else idk. Doubtful tho 😛

2022-07-23 04:17 UTC, Jhavaa commented on styles/globals.css
> +.hope {
tbh I think we should rename this, cause it's pretty ambiguous lol

2022-07-23 04:17 UTC, Jhavaa commented on styles/globals.css
> +.video-responsive {
I remembered you mentioning that there were multiple of these classes, so we should def consider deleting duplicates.

2022-07-23 04:17 UTC, Jhavaa commented on components/FeaturedSlider.js
> +  console.log("---------Game Prop------");
We should avoid merging comments into main, just so we aren't confused by debug console logs in the future. When we start running 'production' level code, we should also avoid any console logs to hide debug code from the user.

2022-07-23 04:17 UTC, Jhavaa commented on components/FeaturedSlider.js
> +        style={{
I haven't explored swiper that much, but is it possible to put these styles in the CSS? Like import the styles the same way we do with tailwind and define a class with these styles. If not dw about it.

2022-07-23 04:17 UTC, Jhavaa commented on components/FeaturedSlider.js
> +                    {/* aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa */}
uhhh... no idea what that is 😂 I would say delete comments, but it's up to you if you see yourself going back to this.

2022-07-25 01:33 UTC, srayce1 approved these changes

2022-07-25 03:39 UTC, Jhavaa approved these changes

2022-07-25 03:39 UTC, merged